//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTMS.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string ID_Bank { get; set; }
        public string BankName { get; set; }
        public string Address01 { get; set; }
        public string Address02 { get; set; }
        public string ID_State { get; set; }
        public Nullable<bool> OpenAccount { get; set; }
        public string BankGlActNo { get; set; }
        public string SwitchCode { get; set; }
        public string BankCode { get; set; }
        public string HQRSortCode { get; set; }
    }
}
