//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTMS.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string Event { get; set; }
        public string Executioner { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
    }
}
