//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTMS.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GsmValidator
    {
        public int ID_GsmFormat { get; set; }
        public string ProviderCode { get; set; }
        public string Gsm1st3Digits { get; set; }
        public Nullable<int> GsmNoLenght { get; set; }
    }
}
