//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTMS.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public int SetUpID { get; set; }
        public string MonthOfOperation { get; set; }
        public Nullable<bool> EnableWeekendProfitAndLossAnalysis { get; set; }
    }
}
