//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTMS.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int TransactionID { get; set; }
        public string TID { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> AmountOutstanding { get; set; }
        public int AccountID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int DealerID { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
        public string CapturedBy { get; set; }
        public string PaymentMode { get; set; }
        public string Narration { get; set; }
        public string Comments { get; set; }
        public int FID { get; set; }
        public string Bank { get; set; }
    }
}
